import { motion } from "motion/react";

export default function DisclaimerPage() {
  return (
    <section className="py-16">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1
            className="font-display font-bold text-4xl mb-2"
            style={{ color: "oklch(0.18 0.065 240)" }}
          >
            Disclaimer
          </h1>
          <p
            className="text-sm mb-8"
            style={{ color: "oklch(0.55 0.018 240)" }}
          >
            Last updated:{" "}
            {new Date().toLocaleDateString("en-IN", {
              timeZone: "Asia/Kolkata",
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          </p>

          <div
            className="prose prose-slate max-w-none space-y-6"
            style={{ color: "oklch(0.35 0.018 240)" }}
          >
            <div
              className="p-4 rounded-lg border-l-4"
              style={{
                background: "oklch(0.52 0.22 25 / 0.06)",
                borderColor: "oklch(0.52 0.22 25)",
              }}
            >
              <p
                className="font-semibold text-sm"
                style={{ color: "oklch(0.35 0.18 25)" }}
              >
                IMPORTANT: This software does not provide investment advice.
                Please read the full disclaimer before using.
              </p>
            </div>

            <h2
              className="font-display font-semibold text-xl"
              style={{ color: "oklch(0.20 0.065 240)" }}
            >
              Not Investment Advice
            </h2>
            <p className="text-sm leading-relaxed">
              Jagdish Portfolio Management Software (PMS) is a personal finance
              tracking tool designed solely for informational and record-keeping
              purposes. Nothing on this website or within the application
              constitutes investment advice, financial advice, trading advice,
              or any other sort of professional advice. You should not make any
              financial decision based solely on the information provided by
              this software.
            </p>

            <h2
              className="font-display font-semibold text-xl"
              style={{ color: "oklch(0.20 0.065 240)" }}
            >
              For Informational Purposes Only
            </h2>
            <p className="text-sm leading-relaxed">
              All data, reports, calculations (including XIRR, capital gains,
              and returns), and information displayed in Jagdish PMS are
              provided for informational and personal tracking purposes only.
              While we strive for accuracy, we do not guarantee that the
              calculations or data are free from errors. Always consult a
              qualified financial advisor or chartered accountant (CA) before
              making investment decisions.
            </p>

            <h2
              className="font-display font-semibold text-xl"
              style={{ color: "oklch(0.20 0.065 240)" }}
            >
              No Warranty
            </h2>
            <p className="text-sm leading-relaxed">
              This software is provided "as is" without any warranty of any
              kind, express or implied, including but not limited to the
              warranties of merchantability, fitness for a particular purpose,
              and non-infringement. In no event shall Jagdish PMS or its
              operators be liable for any direct, indirect, incidental, special,
              exemplary, or consequential damages arising from the use of this
              application.
            </p>

            <h2
              className="font-display font-semibold text-xl"
              style={{ color: "oklch(0.20 0.065 240)" }}
            >
              Tax & Regulatory Compliance
            </h2>
            <p className="text-sm leading-relaxed">
              The capital gains calculations and tax summaries generated by
              Jagdish PMS are based on general understanding of Indian income
              tax rules and should not be treated as definitive tax advice.
              Indian tax laws are subject to change. Always verify with a
              qualified CA or tax consultant for your specific filing
              requirements. Jagdish PMS is not affiliated with SEBI, AMFI, or
              any other regulatory body.
            </p>

            <h2
              className="font-display font-semibold text-xl"
              style={{ color: "oklch(0.20 0.065 240)" }}
            >
              Third-Party Information
            </h2>
            <p className="text-sm leading-relaxed">
              NAV data and fund information entered into the application are
              provided by the user manually. Jagdish PMS does not source or
              verify NAV data from any fund house or AMFI. The accuracy of
              calculations depends entirely on the data entered by the user.
            </p>

            <h2
              className="font-display font-semibold text-xl"
              style={{ color: "oklch(0.20 0.065 240)" }}
            >
              Acceptance
            </h2>
            <p className="text-sm leading-relaxed">
              By using Jagdish Portfolio Management Software, you accept and
              agree to this disclaimer in full. If you disagree with any part of
              this disclaimer, you should not use this application.
            </p>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
