/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FundCategory = IDL.Variant({
  'debt' : IDL.Null,
  'elss' : IDL.Null,
  'hybrid' : IDL.Null,
  'equity' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'buy' : IDL.Null,
  'sip' : IDL.Null,
  'sell' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostStatus = IDL.Variant({
  'published' : IDL.Null,
  'privateVisibility' : IDL.Null,
  'draft' : IDL.Null,
});
export const CreateBlogPostInput = IDL.Record({
  'status' : PostStatus,
  'title' : IDL.Text,
  'content' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const Fund = IDL.Record({
  'id' : IDL.Text,
  'lastNavUpdate' : Time,
  'name' : IDL.Text,
  'category' : FundCategory,
  'currentNav' : IDL.Nat,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'status' : PostStatus,
  'title' : IDL.Text,
  'content' : IDL.Vec(IDL.Text),
  'createdAt' : Time,
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'summary' : IDL.Text,
  'updatedAt' : Time,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FundCapitalGain = IDL.Record({
  'ltcg' : IDL.Nat,
  'stcg' : IDL.Nat,
  'fundId' : IDL.Text,
});
export const CapitalGainsReport = IDL.Record({
  'totalLtcg' : IDL.Nat,
  'totalStcg' : IDL.Nat,
  'details' : IDL.Vec(FundCapitalGain),
});
export const Holding = IDL.Record({
  'fundId' : IDL.Text,
  'units' : IDL.Nat,
  'avgCostNav' : IDL.Nat,
});
export const HoldingSummary = IDL.Record({
  'gainLoss' : IDL.Int,
  'fundId' : IDL.Text,
  'currentValue' : IDL.Nat,
  'units' : IDL.Nat,
  'amountInvested' : IDL.Nat,
});
export const PortfolioSummary = IDL.Record({
  'gainLoss' : IDL.Int,
  'holdings' : IDL.Vec(HoldingSummary),
  'currentValue' : IDL.Nat,
  'investedAmount' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'transactionType' : TransactionType,
  'navPerUnit' : IDL.Nat,
  'date' : Time,
  'fundId' : IDL.Text,
  'units' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const UpdateBlogPostInput = IDL.Record({
  'id' : IDL.Text,
  'status' : PostStatus,
  'title' : IDL.Text,
  'content' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFund' : IDL.Func([IDL.Text, IDL.Text, FundCategory, IDL.Nat], [], []),
  'addTransaction' : IDL.Func(
      [IDL.Text, TransactionType, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([CreateBlogPostInput], [IDL.Text], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'getAllFunds' : IDL.Func([], [IDL.Vec(Fund)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCapitalGainsReport' : IDL.Func([], [CapitalGainsReport], []),
  'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
  'getNextPostId' : IDL.Func([], [IDL.Nat], ['query']),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
  'getPostById' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getPublishedPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateNav' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updatePost' : IDL.Func([UpdateBlogPostInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FundCategory = IDL.Variant({
    'debt' : IDL.Null,
    'elss' : IDL.Null,
    'hybrid' : IDL.Null,
    'equity' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'buy' : IDL.Null,
    'sip' : IDL.Null,
    'sell' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostStatus = IDL.Variant({
    'published' : IDL.Null,
    'privateVisibility' : IDL.Null,
    'draft' : IDL.Null,
  });
  const CreateBlogPostInput = IDL.Record({
    'status' : PostStatus,
    'title' : IDL.Text,
    'content' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const Fund = IDL.Record({
    'id' : IDL.Text,
    'lastNavUpdate' : Time,
    'name' : IDL.Text,
    'category' : FundCategory,
    'currentNav' : IDL.Nat,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'status' : PostStatus,
    'title' : IDL.Text,
    'content' : IDL.Vec(IDL.Text),
    'createdAt' : Time,
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'summary' : IDL.Text,
    'updatedAt' : Time,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FundCapitalGain = IDL.Record({
    'ltcg' : IDL.Nat,
    'stcg' : IDL.Nat,
    'fundId' : IDL.Text,
  });
  const CapitalGainsReport = IDL.Record({
    'totalLtcg' : IDL.Nat,
    'totalStcg' : IDL.Nat,
    'details' : IDL.Vec(FundCapitalGain),
  });
  const Holding = IDL.Record({
    'fundId' : IDL.Text,
    'units' : IDL.Nat,
    'avgCostNav' : IDL.Nat,
  });
  const HoldingSummary = IDL.Record({
    'gainLoss' : IDL.Int,
    'fundId' : IDL.Text,
    'currentValue' : IDL.Nat,
    'units' : IDL.Nat,
    'amountInvested' : IDL.Nat,
  });
  const PortfolioSummary = IDL.Record({
    'gainLoss' : IDL.Int,
    'holdings' : IDL.Vec(HoldingSummary),
    'currentValue' : IDL.Nat,
    'investedAmount' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'transactionType' : TransactionType,
    'navPerUnit' : IDL.Nat,
    'date' : Time,
    'fundId' : IDL.Text,
    'units' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const UpdateBlogPostInput = IDL.Record({
    'id' : IDL.Text,
    'status' : PostStatus,
    'title' : IDL.Text,
    'content' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFund' : IDL.Func([IDL.Text, IDL.Text, FundCategory, IDL.Nat], [], []),
    'addTransaction' : IDL.Func(
        [IDL.Text, TransactionType, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([CreateBlogPostInput], [IDL.Text], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'getAllFunds' : IDL.Func([], [IDL.Vec(Fund)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCapitalGainsReport' : IDL.Func([], [CapitalGainsReport], []),
    'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
    'getNextPostId' : IDL.Func([], [IDL.Nat], ['query']),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
    'getPostById' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getPublishedPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateNav' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updatePost' : IDL.Func([UpdateBlogPostInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };