/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'categories' : Array<string>,
  'status' : PostStatus,
  'title' : string,
  'content' : Array<string>,
  'createdAt' : Time,
  'tags' : Array<string>,
  'author' : string,
  'readTime' : string,
  'summary' : string,
  'updatedAt' : Time,
  'scheduledAt' : [] | [Time],
}
export interface CapitalGainsReport {
  'totalLtcg' : bigint,
  'totalStcg' : bigint,
  'details' : Array<FundCapitalGain>,
}
export interface CreateBlogPostInput {
  'categories' : Array<string>,
  'status' : PostStatus,
  'title' : string,
  'content' : Array<string>,
  'tags' : Array<string>,
  'author' : string,
  'readTime' : string,
  'summary' : string,
  'scheduledAt' : [] | [Time],
}
export interface Fund {
  'id' : string,
  'lastNavUpdate' : Time,
  'name' : string,
  'category' : FundCategory,
  'currentNav' : bigint,
}
export interface FundCapitalGain {
  'ltcg' : bigint,
  'stcg' : bigint,
  'fundId' : string,
}
export type FundCategory = { 'debt' : null } |
  { 'elss' : null } |
  { 'hybrid' : null } |
  { 'equity' : null };
export interface Holding {
  'fundId' : string,
  'units' : bigint,
  'avgCostNav' : bigint,
}
export interface HoldingSummary {
  'gainLoss' : bigint,
  'fundId' : string,
  'currentValue' : bigint,
  'units' : bigint,
  'amountInvested' : bigint,
}
export interface PortfolioSummary {
  'gainLoss' : bigint,
  'holdings' : Array<HoldingSummary>,
  'currentValue' : bigint,
  'investedAmount' : bigint,
}
export type PostStatus = { 'published' : null } |
  { 'privateVisibility' : null } |
  { 'draft' : null };
export type Time = bigint;
export interface Transaction {
  'amc' : [] | [string],
  'folioNumber' : [] | [string],
  'transactionType' : TransactionType,
  'navPerUnit' : bigint,
  'bankAccount' : [] | [string],
  'date' : Time,
  'isin' : [] | [string],
  'agentCode' : [] | [string],
  'agentName' : [] | [string],
  'txnDate' : [] | [bigint],
  'fundId' : string,
  'units' : bigint,
  'paymentMode' : [] | [string],
  'amount' : bigint,
  'remarks' : [] | [string],
  'subAgentCode' : [] | [string],
  'subAgentName' : [] | [string],
}
export interface TransactionInput {
  'amc' : [] | [string],
  'folioNumber' : [] | [string],
  'transactionType' : TransactionType,
  'navPerUnit' : bigint,
  'bankAccount' : [] | [string],
  'isin' : [] | [string],
  'agentCode' : [] | [string],
  'agentName' : [] | [string],
  'txnDate' : [] | [bigint],
  'fundId' : string,
  'units' : bigint,
  'paymentMode' : [] | [string],
  'amount' : bigint,
  'remarks' : [] | [string],
  'subAgentCode' : [] | [string],
  'subAgentName' : [] | [string],
}
export type TransactionType = { 'buy' : null } |
  { 'sip' : null } |
  { 'sell' : null };
export interface UpdateBlogPostInput {
  'id' : string,
  'categories' : Array<string>,
  'status' : PostStatus,
  'title' : string,
  'content' : Array<string>,
  'tags' : Array<string>,
  'author' : string,
  'readTime' : string,
  'summary' : string,
  'scheduledAt' : [] | [Time],
}
export interface UserCapitalGainsRecord {
  'userName' : string,
  'principal' : string,
  'ltcg' : bigint,
  'stcg' : bigint,
  'fundId' : string,
}
export interface UserHoldingRecord {
  'userName' : string,
  'principal' : string,
  'fundId' : string,
  'units' : bigint,
  'avgCostNav' : bigint,
}
export interface UserPortfolio {
  'holdings' : Array<Holding>,
  'transactions' : Array<Transaction>,
  'capitalGains' : CapitalGainsReport,
}
export interface UserProfile {
  'name' : string,
  'gmail' : string,
  'registeredAt' : bigint,
  'lastSeen' : bigint,
}
export interface UserRecord {
  'principal' : string,
  'name' : string,
  'gmail' : string,
  'registeredAt' : bigint,
  'lastSeen' : bigint,
}
export interface UserRegistration { 'name' : string, 'gmail' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'principal' : string,
  'totalInvested' : bigint,
  'gmail' : string,
  'registeredAt' : bigint,
  'lastSeen' : bigint,
  'transactionCount' : bigint,
}
export interface UserTransactionRecord {
  'amc' : [] | [string],
  'folioNumber' : [] | [string],
  'userName' : string,
  'principal' : string,
  'transactionType' : string,
  'navPerUnit' : bigint,
  'bankAccount' : [] | [string],
  'date' : Time,
  'isin' : [] | [string],
  'agentCode' : [] | [string],
  'agentName' : [] | [string],
  'txnDate' : [] | [bigint],
  'fundId' : string,
  'units' : bigint,
  'paymentMode' : [] | [string],
  'amount' : bigint,
  'remarks' : [] | [string],
  'subAgentCode' : [] | [string],
  'subAgentName' : [] | [string],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], undefined>,
  'addFund' : ActorMethod<[string, string, FundCategory, bigint], undefined>,
  'addTag' : ActorMethod<[string], undefined>,
  'addTransaction' : ActorMethod<[TransactionInput], undefined>,
  'adminGetAllCapitalGains' : ActorMethod<[], Array<UserCapitalGainsRecord>>,
  'adminGetAllHoldings' : ActorMethod<[], Array<UserHoldingRecord>>,
  'adminGetAllTransactions' : ActorMethod<[], Array<UserTransactionRecord>>,
  'adminGetAllUsers' : ActorMethod<[], Array<UserRecord>>,
  'adminRescheduleAllPosts' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapFirstAdmin' : ActorMethod<[], boolean>,
  'createPost' : ActorMethod<[CreateBlogPostInput], string>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'deleteTag' : ActorMethod<[string], undefined>,
  'getAdminUserList' : ActorMethod<[], Array<UserSummary>>,
  'getAdminUserPortfolio' : ActorMethod<[Principal], [] | [UserPortfolio]>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllFunds' : ActorMethod<[], Array<Fund>>,
  'getAllPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllTags' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCapitalGainsReport' : ActorMethod<[], CapitalGainsReport>,
  'getHoldings' : ActorMethod<[], Array<Holding>>,
  'getNextPostId' : ActorMethod<[], bigint>,
  'getPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getPostById' : ActorMethod<[string], [] | [BlogPost]>,
  'getPublishedPosts' : ActorMethod<[], Array<BlogPost>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[UserRegistration], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateNav' : ActorMethod<[string, bigint], undefined>,
  'updatePost' : ActorMethod<[UpdateBlogPostInput], undefined>,
  'updatePostSchedule' : ActorMethod<[string, [] | [Time]], undefined>,
  'userSession' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];