/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FundCategory = IDL.Variant({
  'debt' : IDL.Null,
  'elss' : IDL.Null,
  'hybrid' : IDL.Null,
  'equity' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'buy' : IDL.Null,
  'sip' : IDL.Null,
  'sell' : IDL.Null,
});
export const TransactionInput = IDL.Record({
  'amc' : IDL.Opt(IDL.Text),
  'folioNumber' : IDL.Opt(IDL.Text),
  'transactionType' : TransactionType,
  'navPerUnit' : IDL.Nat,
  'bankAccount' : IDL.Opt(IDL.Text),
  'isin' : IDL.Opt(IDL.Text),
  'agentCode' : IDL.Opt(IDL.Text),
  'agentName' : IDL.Opt(IDL.Text),
  'txnDate' : IDL.Opt(IDL.Nat),
  'fundId' : IDL.Text,
  'units' : IDL.Nat,
  'paymentMode' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'remarks' : IDL.Opt(IDL.Text),
  'subAgentCode' : IDL.Opt(IDL.Text),
  'subAgentName' : IDL.Opt(IDL.Text),
});
export const UserCapitalGainsRecord = IDL.Record({
  'userName' : IDL.Text,
  'principal' : IDL.Text,
  'ltcg' : IDL.Nat,
  'stcg' : IDL.Nat,
  'fundId' : IDL.Text,
});
export const UserHoldingRecord = IDL.Record({
  'userName' : IDL.Text,
  'principal' : IDL.Text,
  'fundId' : IDL.Text,
  'units' : IDL.Nat,
  'avgCostNav' : IDL.Nat,
});
export const Time = IDL.Int;
export const UserTransactionRecord = IDL.Record({
  'amc' : IDL.Opt(IDL.Text),
  'folioNumber' : IDL.Opt(IDL.Text),
  'userName' : IDL.Text,
  'principal' : IDL.Text,
  'transactionType' : IDL.Text,
  'navPerUnit' : IDL.Nat,
  'bankAccount' : IDL.Opt(IDL.Text),
  'date' : Time,
  'isin' : IDL.Opt(IDL.Text),
  'agentCode' : IDL.Opt(IDL.Text),
  'agentName' : IDL.Opt(IDL.Text),
  'txnDate' : IDL.Opt(IDL.Nat),
  'fundId' : IDL.Text,
  'units' : IDL.Nat,
  'paymentMode' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'remarks' : IDL.Opt(IDL.Text),
  'subAgentCode' : IDL.Opt(IDL.Text),
  'subAgentName' : IDL.Opt(IDL.Text),
});
export const UserRecord = IDL.Record({
  'principal' : IDL.Text,
  'name' : IDL.Text,
  'gmail' : IDL.Text,
  'registeredAt' : IDL.Int,
  'lastSeen' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostStatus = IDL.Variant({
  'published' : IDL.Null,
  'privateVisibility' : IDL.Null,
  'draft' : IDL.Null,
});
export const CreateBlogPostInput = IDL.Record({
  'categories' : IDL.Vec(IDL.Text),
  'status' : PostStatus,
  'title' : IDL.Text,
  'content' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'summary' : IDL.Text,
  'scheduledAt' : IDL.Opt(Time),
});
export const UserSummary = IDL.Record({
  'principal' : IDL.Text,
  'totalInvested' : IDL.Nat,
  'gmail' : IDL.Text,
  'registeredAt' : IDL.Int,
  'lastSeen' : IDL.Int,
  'transactionCount' : IDL.Nat,
});
export const Holding = IDL.Record({
  'fundId' : IDL.Text,
  'units' : IDL.Nat,
  'avgCostNav' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'amc' : IDL.Opt(IDL.Text),
  'folioNumber' : IDL.Opt(IDL.Text),
  'transactionType' : TransactionType,
  'navPerUnit' : IDL.Nat,
  'bankAccount' : IDL.Opt(IDL.Text),
  'date' : Time,
  'isin' : IDL.Opt(IDL.Text),
  'agentCode' : IDL.Opt(IDL.Text),
  'agentName' : IDL.Opt(IDL.Text),
  'txnDate' : IDL.Opt(IDL.Nat),
  'fundId' : IDL.Text,
  'units' : IDL.Nat,
  'paymentMode' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'remarks' : IDL.Opt(IDL.Text),
  'subAgentCode' : IDL.Opt(IDL.Text),
  'subAgentName' : IDL.Opt(IDL.Text),
});
export const FundCapitalGain = IDL.Record({
  'ltcg' : IDL.Nat,
  'stcg' : IDL.Nat,
  'fundId' : IDL.Text,
});
export const CapitalGainsReport = IDL.Record({
  'totalLtcg' : IDL.Nat,
  'totalStcg' : IDL.Nat,
  'details' : IDL.Vec(FundCapitalGain),
});
export const UserPortfolio = IDL.Record({
  'holdings' : IDL.Vec(Holding),
  'transactions' : IDL.Vec(Transaction),
  'capitalGains' : CapitalGainsReport,
});
export const Fund = IDL.Record({
  'id' : IDL.Text,
  'lastNavUpdate' : Time,
  'name' : IDL.Text,
  'category' : FundCategory,
  'currentNav' : IDL.Nat,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'status' : PostStatus,
  'title' : IDL.Text,
  'content' : IDL.Vec(IDL.Text),
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'summary' : IDL.Text,
  'updatedAt' : Time,
  'scheduledAt' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'gmail' : IDL.Text,
  'registeredAt' : IDL.Int,
  'lastSeen' : IDL.Int,
});
export const HoldingSummary = IDL.Record({
  'gainLoss' : IDL.Int,
  'fundId' : IDL.Text,
  'currentValue' : IDL.Nat,
  'units' : IDL.Nat,
  'amountInvested' : IDL.Nat,
});
export const PortfolioSummary = IDL.Record({
  'gainLoss' : IDL.Int,
  'holdings' : IDL.Vec(HoldingSummary),
  'currentValue' : IDL.Nat,
  'investedAmount' : IDL.Nat,
});
export const UserRegistration = IDL.Record({
  'name' : IDL.Text,
  'gmail' : IDL.Text,
});
export const UpdateBlogPostInput = IDL.Record({
  'id' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'status' : PostStatus,
  'title' : IDL.Text,
  'content' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'readTime' : IDL.Text,
  'summary' : IDL.Text,
  'scheduledAt' : IDL.Opt(Time),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text], [], []),
  'addFund' : IDL.Func([IDL.Text, IDL.Text, FundCategory, IDL.Nat], [], []),
  'addTag' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func([TransactionInput], [], []),
  'adminGetAllCapitalGains' : IDL.Func(
      [],
      [IDL.Vec(UserCapitalGainsRecord)],
      ['query'],
    ),
  'adminGetAllHoldings' : IDL.Func([], [IDL.Vec(UserHoldingRecord)], ['query']),
  'adminGetAllTransactions' : IDL.Func(
      [],
      [IDL.Vec(UserTransactionRecord)],
      ['query'],
    ),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
  'adminRescheduleAllPosts' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'createPost' : IDL.Func([CreateBlogPostInput], [IDL.Text], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'deleteTag' : IDL.Func([IDL.Text], [], []),
  'getAdminUserList' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'getAdminUserPortfolio' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserPortfolio)],
      ['query'],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllFunds' : IDL.Func([], [IDL.Vec(Fund)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCapitalGainsReport' : IDL.Func([], [CapitalGainsReport], ['query']),
  'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
  'getNextPostId' : IDL.Func([], [IDL.Nat], ['query']),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
  'getPostById' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getPublishedPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([UserRegistration], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateNav' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updatePost' : IDL.Func([UpdateBlogPostInput], [], []),
  'updatePostSchedule' : IDL.Func([IDL.Text, IDL.Opt(Time)], [], []),
  'userSession' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FundCategory = IDL.Variant({
    'debt' : IDL.Null,
    'elss' : IDL.Null,
    'hybrid' : IDL.Null,
    'equity' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'buy' : IDL.Null,
    'sip' : IDL.Null,
    'sell' : IDL.Null,
  });
  const TransactionInput = IDL.Record({
    'amc' : IDL.Opt(IDL.Text),
    'folioNumber' : IDL.Opt(IDL.Text),
    'transactionType' : TransactionType,
    'navPerUnit' : IDL.Nat,
    'bankAccount' : IDL.Opt(IDL.Text),
    'isin' : IDL.Opt(IDL.Text),
    'agentCode' : IDL.Opt(IDL.Text),
    'agentName' : IDL.Opt(IDL.Text),
    'txnDate' : IDL.Opt(IDL.Nat),
    'fundId' : IDL.Text,
    'units' : IDL.Nat,
    'paymentMode' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'remarks' : IDL.Opt(IDL.Text),
    'subAgentCode' : IDL.Opt(IDL.Text),
    'subAgentName' : IDL.Opt(IDL.Text),
  });
  const UserCapitalGainsRecord = IDL.Record({
    'userName' : IDL.Text,
    'principal' : IDL.Text,
    'ltcg' : IDL.Nat,
    'stcg' : IDL.Nat,
    'fundId' : IDL.Text,
  });
  const UserHoldingRecord = IDL.Record({
    'userName' : IDL.Text,
    'principal' : IDL.Text,
    'fundId' : IDL.Text,
    'units' : IDL.Nat,
    'avgCostNav' : IDL.Nat,
  });
  const Time = IDL.Int;
  const UserTransactionRecord = IDL.Record({
    'amc' : IDL.Opt(IDL.Text),
    'folioNumber' : IDL.Opt(IDL.Text),
    'userName' : IDL.Text,
    'principal' : IDL.Text,
    'transactionType' : IDL.Text,
    'navPerUnit' : IDL.Nat,
    'bankAccount' : IDL.Opt(IDL.Text),
    'date' : Time,
    'isin' : IDL.Opt(IDL.Text),
    'agentCode' : IDL.Opt(IDL.Text),
    'agentName' : IDL.Opt(IDL.Text),
    'txnDate' : IDL.Opt(IDL.Nat),
    'fundId' : IDL.Text,
    'units' : IDL.Nat,
    'paymentMode' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'remarks' : IDL.Opt(IDL.Text),
    'subAgentCode' : IDL.Opt(IDL.Text),
    'subAgentName' : IDL.Opt(IDL.Text),
  });
  const UserRecord = IDL.Record({
    'principal' : IDL.Text,
    'name' : IDL.Text,
    'gmail' : IDL.Text,
    'registeredAt' : IDL.Int,
    'lastSeen' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostStatus = IDL.Variant({
    'published' : IDL.Null,
    'privateVisibility' : IDL.Null,
    'draft' : IDL.Null,
  });
  const CreateBlogPostInput = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'status' : PostStatus,
    'title' : IDL.Text,
    'content' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'summary' : IDL.Text,
    'scheduledAt' : IDL.Opt(Time),
  });
  const UserSummary = IDL.Record({
    'principal' : IDL.Text,
    'totalInvested' : IDL.Nat,
    'gmail' : IDL.Text,
    'registeredAt' : IDL.Int,
    'lastSeen' : IDL.Int,
    'transactionCount' : IDL.Nat,
  });
  const Holding = IDL.Record({
    'fundId' : IDL.Text,
    'units' : IDL.Nat,
    'avgCostNav' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'amc' : IDL.Opt(IDL.Text),
    'folioNumber' : IDL.Opt(IDL.Text),
    'transactionType' : TransactionType,
    'navPerUnit' : IDL.Nat,
    'bankAccount' : IDL.Opt(IDL.Text),
    'date' : Time,
    'isin' : IDL.Opt(IDL.Text),
    'agentCode' : IDL.Opt(IDL.Text),
    'agentName' : IDL.Opt(IDL.Text),
    'txnDate' : IDL.Opt(IDL.Nat),
    'fundId' : IDL.Text,
    'units' : IDL.Nat,
    'paymentMode' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'remarks' : IDL.Opt(IDL.Text),
    'subAgentCode' : IDL.Opt(IDL.Text),
    'subAgentName' : IDL.Opt(IDL.Text),
  });
  const FundCapitalGain = IDL.Record({
    'ltcg' : IDL.Nat,
    'stcg' : IDL.Nat,
    'fundId' : IDL.Text,
  });
  const CapitalGainsReport = IDL.Record({
    'totalLtcg' : IDL.Nat,
    'totalStcg' : IDL.Nat,
    'details' : IDL.Vec(FundCapitalGain),
  });
  const UserPortfolio = IDL.Record({
    'holdings' : IDL.Vec(Holding),
    'transactions' : IDL.Vec(Transaction),
    'capitalGains' : CapitalGainsReport,
  });
  const Fund = IDL.Record({
    'id' : IDL.Text,
    'lastNavUpdate' : Time,
    'name' : IDL.Text,
    'category' : FundCategory,
    'currentNav' : IDL.Nat,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'status' : PostStatus,
    'title' : IDL.Text,
    'content' : IDL.Vec(IDL.Text),
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'summary' : IDL.Text,
    'updatedAt' : Time,
    'scheduledAt' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'gmail' : IDL.Text,
    'registeredAt' : IDL.Int,
    'lastSeen' : IDL.Int,
  });
  const HoldingSummary = IDL.Record({
    'gainLoss' : IDL.Int,
    'fundId' : IDL.Text,
    'currentValue' : IDL.Nat,
    'units' : IDL.Nat,
    'amountInvested' : IDL.Nat,
  });
  const PortfolioSummary = IDL.Record({
    'gainLoss' : IDL.Int,
    'holdings' : IDL.Vec(HoldingSummary),
    'currentValue' : IDL.Nat,
    'investedAmount' : IDL.Nat,
  });
  const UserRegistration = IDL.Record({
    'name' : IDL.Text,
    'gmail' : IDL.Text,
  });
  const UpdateBlogPostInput = IDL.Record({
    'id' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'status' : PostStatus,
    'title' : IDL.Text,
    'content' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'readTime' : IDL.Text,
    'summary' : IDL.Text,
    'scheduledAt' : IDL.Opt(Time),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text], [], []),
    'addFund' : IDL.Func([IDL.Text, IDL.Text, FundCategory, IDL.Nat], [], []),
    'addTag' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func([TransactionInput], [], []),
    'adminGetAllCapitalGains' : IDL.Func(
        [],
        [IDL.Vec(UserCapitalGainsRecord)],
        ['query'],
      ),
    'adminGetAllHoldings' : IDL.Func(
        [],
        [IDL.Vec(UserHoldingRecord)],
        ['query'],
      ),
    'adminGetAllTransactions' : IDL.Func(
        [],
        [IDL.Vec(UserTransactionRecord)],
        ['query'],
      ),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
    'adminRescheduleAllPosts' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'createPost' : IDL.Func([CreateBlogPostInput], [IDL.Text], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'deleteTag' : IDL.Func([IDL.Text], [], []),
    'getAdminUserList' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'getAdminUserPortfolio' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserPortfolio)],
        ['query'],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllFunds' : IDL.Func([], [IDL.Vec(Fund)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCapitalGainsReport' : IDL.Func([], [CapitalGainsReport], ['query']),
    'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
    'getNextPostId' : IDL.Func([], [IDL.Nat], ['query']),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
    'getPostById' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getPublishedPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([UserRegistration], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateNav' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updatePost' : IDL.Func([UpdateBlogPostInput], [], []),
    'updatePostSchedule' : IDL.Func([IDL.Text, IDL.Opt(Time)], [], []),
    'userSession' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };