/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CapitalGainsReport {
    totalLtcg: bigint;
    totalStcg: bigint;
    details: Array<FundCapitalGain>;
}
export interface BlogPost {
    id: string;
    status: PostStatus;
    title: string;
    content: Array<string>;
    createdAt: Time;
    author: string;
    readTime: string;
    summary: string;
    updatedAt: Time;
    category: string;
}
export type Time = bigint;
export interface HoldingSummary {
    gainLoss: bigint;
    fundId: string;
    currentValue: bigint;
    units: bigint;
    amountInvested: bigint;
}
export interface PortfolioSummary {
    gainLoss: bigint;
    holdings: Array<HoldingSummary>;
    currentValue: bigint;
    investedAmount: bigint;
}
export interface FundCapitalGain {
    ltcg: bigint;
    stcg: bigint;
    fundId: string;
}
export interface UpdateBlogPostInput {
    id: string;
    status: PostStatus;
    title: string;
    content: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    category: string;
}
export interface Transaction {
    transactionType: TransactionType;
    navPerUnit: bigint;
    date: Time;
    fundId: string;
    units: bigint;
    amount: bigint;
}
export interface CreateBlogPostInput {
    status: PostStatus;
    title: string;
    content: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    category: string;
}
export interface Holding {
    fundId: string;
    units: bigint;
    avgCostNav: bigint;
}
export interface Fund {
    id: string;
    lastNavUpdate: Time;
    name: string;
    category: FundCategory;
    currentNav: bigint;
}
export interface UserProfile {
    name: string;
}
export enum FundCategory {
    debt = "debt",
    elss = "elss",
    hybrid = "hybrid",
    equity = "equity"
}
export enum PostStatus {
    published = "published",
    privateVisibility = "privateVisibility",
    draft = "draft"
}
export enum TransactionType {
    buy = "buy",
    sip = "sip",
    sell = "sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFund(id: string, name: string, category: FundCategory, initialNav: bigint): Promise<void>;
    addTransaction(fundId: string, transactionType: TransactionType, units: bigint, navPerUnit: bigint, amount: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPost(input: CreateBlogPostInput): Promise<string>;
    deletePost(postId: string): Promise<void>;
    getAllFunds(): Promise<Array<Fund>>;
    getAllPosts(): Promise<Array<BlogPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCapitalGainsReport(): Promise<CapitalGainsReport>;
    getHoldings(): Promise<Array<Holding>>;
    getNextPostId(): Promise<bigint>;
    getPortfolioSummary(): Promise<PortfolioSummary>;
    getPostById(postId: string): Promise<BlogPost | null>;
    getPublishedPosts(): Promise<Array<BlogPost>>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateNav(fundId: string, newNav: bigint): Promise<void>;
    updatePost(input: UpdateBlogPostInput): Promise<void>;
}
import type { BlogPost as _BlogPost, CreateBlogPostInput as _CreateBlogPostInput, Fund as _Fund, FundCategory as _FundCategory, PostStatus as _PostStatus, Time as _Time, Transaction as _Transaction, TransactionType as _TransactionType, UpdateBlogPostInput as _UpdateBlogPostInput, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFund(arg0: string, arg1: string, arg2: FundCategory, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFund(arg0, arg1, to_candid_FundCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFund(arg0, arg1, to_candid_FundCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addTransaction(arg0: string, arg1: TransactionType, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, to_candid_TransactionType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, to_candid_TransactionType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPost(arg0: CreateBlogPostInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_CreateBlogPostInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_CreateBlogPostInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deletePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async getAllFunds(): Promise<Array<Fund>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFunds();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFunds();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCapitalGainsReport(): Promise<CapitalGainsReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getCapitalGainsReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCapitalGainsReport();
            return result;
        }
    }
    async getHoldings(): Promise<Array<Holding>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHoldings();
            return result;
        }
    }
    async getNextPostId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextPostId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextPostId();
            return result;
        }
    }
    async getPortfolioSummary(): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary();
            return result;
        }
    }
    async getPostById(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPosts();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPosts();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateNav(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNav(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNav(arg0, arg1);
            return result;
        }
    }
    async updatePost(arg0: UpdateBlogPostInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePost(to_candid_UpdateBlogPostInput_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePost(to_candid_UpdateBlogPostInput_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BlogPost_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): BlogPost {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_FundCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundCategory): FundCategory {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Fund_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fund): Fund {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PostStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostStatus): PostStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : from_candid_BlogPost_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lastNavUpdate: _Time;
    name: string;
    category: _FundCategory;
    currentNav: bigint;
}): {
    id: string;
    lastNavUpdate: Time;
    name: string;
    category: FundCategory;
    currentNav: bigint;
} {
    return {
        id: value.id,
        lastNavUpdate: value.lastNavUpdate,
        name: value.name,
        category: from_candid_FundCategory_n14(_uploadFile, _downloadFile, value.category),
        currentNav: value.currentNav
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PostStatus;
    title: string;
    content: Array<string>;
    createdAt: _Time;
    author: string;
    readTime: string;
    summary: string;
    updatedAt: _Time;
    category: string;
}): {
    id: string;
    status: PostStatus;
    title: string;
    content: Array<string>;
    createdAt: Time;
    author: string;
    readTime: string;
    summary: string;
    updatedAt: Time;
    category: string;
} {
    return {
        id: value.id,
        status: from_candid_PostStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        author: value.author,
        readTime: value.readTime,
        summary: value.summary,
        updatedAt: value.updatedAt,
        category: value.category
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: _TransactionType;
    navPerUnit: bigint;
    date: _Time;
    fundId: string;
    units: bigint;
    amount: bigint;
}): {
    transactionType: TransactionType;
    navPerUnit: bigint;
    date: Time;
    fundId: string;
    units: bigint;
    amount: bigint;
} {
    return {
        transactionType: from_candid_TransactionType_n28(_uploadFile, _downloadFile, value.transactionType),
        navPerUnit: value.navPerUnit,
        date: value.date,
        fundId: value.fundId,
        units: value.units,
        amount: value.amount
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    debt: null;
} | {
    elss: null;
} | {
    hybrid: null;
} | {
    equity: null;
}): FundCategory {
    return "debt" in value ? FundCategory.debt : "elss" in value ? FundCategory.elss : "hybrid" in value ? FundCategory.hybrid : "equity" in value ? FundCategory.equity : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    privateVisibility: null;
} | {
    draft: null;
}): PostStatus {
    return "published" in value ? PostStatus.published : "privateVisibility" in value ? PostStatus.privateVisibility : "draft" in value ? PostStatus.draft : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sip: null;
} | {
    sell: null;
}): TransactionType {
    return "buy" in value ? TransactionType.buy : "sip" in value ? TransactionType.sip : "sell" in value ? TransactionType.sell : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fund>): Array<Fund> {
    return value.map((x)=>from_candid_Fund_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Array<BlogPost> {
    return value.map((x)=>from_candid_BlogPost_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n26(_uploadFile, _downloadFile, x));
}
function to_candid_CreateBlogPostInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBlogPostInput): _CreateBlogPostInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_FundCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundCategory): _FundCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PostStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): _PostStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateBlogPostInput_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateBlogPostInput): _UpdateBlogPostInput {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: PostStatus;
    title: string;
    content: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    category: string;
}): {
    id: string;
    status: _PostStatus;
    title: string;
    content: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    category: string;
} {
    return {
        id: value.id,
        status: to_candid_PostStatus_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        author: value.author,
        readTime: value.readTime,
        summary: value.summary,
        category: value.category
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PostStatus;
    title: string;
    content: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    category: string;
}): {
    status: _PostStatus;
    title: string;
    content: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    category: string;
} {
    return {
        status: to_candid_PostStatus_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        author: value.author,
        readTime: value.readTime,
        summary: value.summary,
        category: value.category
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): {
    published: null;
} | {
    privateVisibility: null;
} | {
    draft: null;
} {
    return value == PostStatus.published ? {
        published: null
    } : value == PostStatus.privateVisibility ? {
        privateVisibility: null
    } : value == PostStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundCategory): {
    debt: null;
} | {
    elss: null;
} | {
    hybrid: null;
} | {
    equity: null;
} {
    return value == FundCategory.debt ? {
        debt: null
    } : value == FundCategory.elss ? {
        elss: null
    } : value == FundCategory.hybrid ? {
        hybrid: null
    } : value == FundCategory.equity ? {
        equity: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    buy: null;
} | {
    sip: null;
} | {
    sell: null;
} {
    return value == TransactionType.buy ? {
        buy: null
    } : value == TransactionType.sip ? {
        sip: null
    } : value == TransactionType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
