/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserTransactionRecord {
    amc?: string;
    folioNumber?: string;
    userName: string;
    principal: string;
    transactionType: string;
    navPerUnit: bigint;
    bankAccount?: string;
    date: Time;
    isin?: string;
    agentCode?: string;
    agentName?: string;
    txnDate?: bigint;
    fundId: string;
    units: bigint;
    paymentMode?: string;
    amount: bigint;
    remarks?: string;
    subAgentCode?: string;
    subAgentName?: string;
}
export interface CapitalGainsReport {
    totalLtcg: bigint;
    totalStcg: bigint;
    details: Array<FundCapitalGain>;
}
export interface BlogPost {
    id: string;
    categories: Array<string>;
    status: PostStatus;
    title: string;
    content: Array<string>;
    createdAt: Time;
    tags: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    updatedAt: Time;
    scheduledAt?: Time;
}
export type Time = bigint;
export interface UserHoldingRecord {
    userName: string;
    principal: string;
    fundId: string;
    units: bigint;
    avgCostNav: bigint;
}
export interface HoldingSummary {
    gainLoss: bigint;
    fundId: string;
    currentValue: bigint;
    units: bigint;
    amountInvested: bigint;
}
export interface UserPortfolio {
    holdings: Array<Holding>;
    transactions: Array<Transaction>;
    capitalGains: CapitalGainsReport;
}
export interface PortfolioSummary {
    gainLoss: bigint;
    holdings: Array<HoldingSummary>;
    currentValue: bigint;
    investedAmount: bigint;
}
export interface FundCapitalGain {
    ltcg: bigint;
    stcg: bigint;
    fundId: string;
}
export interface UpdateBlogPostInput {
    id: string;
    categories: Array<string>;
    status: PostStatus;
    title: string;
    content: Array<string>;
    tags: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    scheduledAt?: Time;
}
export interface UserRecord {
    principal: string;
    name: string;
    gmail: string;
    registeredAt: bigint;
    lastSeen: bigint;
}
export interface Transaction {
    amc?: string;
    folioNumber?: string;
    transactionType: TransactionType;
    navPerUnit: bigint;
    bankAccount?: string;
    date: Time;
    isin?: string;
    agentCode?: string;
    agentName?: string;
    txnDate?: bigint;
    fundId: string;
    units: bigint;
    paymentMode?: string;
    amount: bigint;
    remarks?: string;
    subAgentCode?: string;
    subAgentName?: string;
}
export interface CreateBlogPostInput {
    categories: Array<string>;
    status: PostStatus;
    title: string;
    content: Array<string>;
    tags: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    scheduledAt?: Time;
}
export interface UserRegistration {
    name: string;
    gmail: string;
}
export interface UserCapitalGainsRecord {
    userName: string;
    principal: string;
    ltcg: bigint;
    stcg: bigint;
    fundId: string;
}
export interface UserSummary {
    principal: string;
    totalInvested: bigint;
    gmail: string;
    registeredAt: bigint;
    lastSeen: bigint;
    transactionCount: bigint;
}
export interface Holding {
    fundId: string;
    units: bigint;
    avgCostNav: bigint;
}
export interface Fund {
    id: string;
    amc: string;
    lastNavUpdate: Time;
    name: string;
    fundType: string;
    category: FundCategory;
    currentNav: bigint;
}
export interface TransactionInput {
    amc?: string;
    folioNumber?: string;
    transactionType: TransactionType;
    navPerUnit: bigint;
    bankAccount?: string;
    isin?: string;
    agentCode?: string;
    agentName?: string;
    txnDate?: bigint;
    fundId: string;
    units: bigint;
    paymentMode?: string;
    amount: bigint;
    remarks?: string;
    subAgentCode?: string;
    subAgentName?: string;
}
export interface UserProfile {
    name: string;
    gmail: string;
    registeredAt: bigint;
    lastSeen: bigint;
}
export enum FundCategory {
    debt = "debt",
    elss = "elss",
    hybrid = "hybrid",
    equity = "equity"
}
export enum PostStatus {
    published = "published",
    privateVisibility = "privateVisibility",
    draft = "draft"
}
export enum TransactionType {
    buy = "buy",
    sip = "sip",
    sell = "sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCategory(category: string): Promise<void>;
    addFavoriteFund(fundId: string): Promise<void>;
    addFund(id: string, name: string, category: FundCategory, initialNav: bigint, amc: string, fundType: string): Promise<void>;
    addTag(tag: string): Promise<void>;
    addTransaction(input: TransactionInput): Promise<void>;
    adminGetAllCapitalGains(): Promise<Array<UserCapitalGainsRecord>>;
    adminGetAllHoldings(): Promise<Array<UserHoldingRecord>>;
    adminGetAllTransactions(): Promise<Array<UserTransactionRecord>>;
    adminGetAllUsers(): Promise<Array<UserRecord>>;
    adminRescheduleAllPosts(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bootstrapFirstAdmin(): Promise<boolean>;
    createPost(input: CreateBlogPostInput): Promise<string>;
    deleteCategory(category: string): Promise<void>;
    deletePost(postId: string): Promise<void>;
    deleteTag(tag: string): Promise<void>;
    getAdminUserList(): Promise<Array<UserSummary>>;
    getAdminUserPortfolio(id: Principal): Promise<UserPortfolio | null>;
    getAllCategories(): Promise<Array<string>>;
    getAllFunds(): Promise<Array<Fund>>;
    getAllPosts(): Promise<Array<BlogPost>>;
    getAllTags(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCapitalGainsReport(): Promise<CapitalGainsReport>;
    getFavoriteFunds(): Promise<Array<string>>;
    getHoldings(): Promise<Array<Holding>>;
    getNextPostId(): Promise<bigint>;
    getPortfolioSummary(): Promise<PortfolioSummary>;
    getPostById(postId: string): Promise<BlogPost | null>;
    getPublishedPosts(): Promise<Array<BlogPost>>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isFundFavorite(fundId: string): Promise<boolean>;
    registerUser(arg0: UserRegistration): Promise<void>;
    removeFavoriteFund(fundId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateNav(fundId: string, newNav: bigint): Promise<void>;
    updatePost(input: UpdateBlogPostInput): Promise<void>;
    updatePostSchedule(postId: string, scheduledAt: Time | null): Promise<void>;
    userSession(): Promise<void>;
}
import type { BlogPost as _BlogPost, CapitalGainsReport as _CapitalGainsReport, CreateBlogPostInput as _CreateBlogPostInput, Fund as _Fund, FundCategory as _FundCategory, Holding as _Holding, PostStatus as _PostStatus, Time as _Time, Transaction as _Transaction, TransactionInput as _TransactionInput, TransactionType as _TransactionType, UpdateBlogPostInput as _UpdateBlogPostInput, UserPortfolio as _UserPortfolio, UserProfile as _UserProfile, UserRole as _UserRole, UserTransactionRecord as _UserTransactionRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0);
            return result;
        }
    }
    async addFavoriteFund(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoriteFund(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoriteFund(arg0);
            return result;
        }
    }
    async addFund(arg0: string, arg1: string, arg2: FundCategory, arg3: bigint, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFund(arg0, arg1, to_candid_FundCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFund(arg0, arg1, to_candid_FundCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async addTag(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTag(arg0);
            return result;
        }
    }
    async addTransaction(arg0: TransactionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_TransactionInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_TransactionInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminGetAllCapitalGains(): Promise<Array<UserCapitalGainsRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllCapitalGains();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllCapitalGains();
            return result;
        }
    }
    async adminGetAllHoldings(): Promise<Array<UserHoldingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllHoldings();
            return result;
        }
    }
    async adminGetAllTransactions(): Promise<Array<UserTransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTransactions();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTransactions();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllUsers(): Promise<Array<UserRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return result;
        }
    }
    async adminRescheduleAllPosts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRescheduleAllPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRescheduleAllPosts();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bootstrapFirstAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapFirstAdmin();
            return result;
        }
    }
    async createPost(arg0: CreateBlogPostInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_CreateBlogPostInput_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_CreateBlogPostInput_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deletePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteTag(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTag(arg0);
            return result;
        }
    }
    async getAdminUserList(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUserList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUserList();
            return result;
        }
    }
    async getAdminUserPortfolio(arg0: Principal): Promise<UserPortfolio | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUserPortfolio(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUserPortfolio(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllFunds(): Promise<Array<Fund>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFunds();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFunds();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTags(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTags();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCapitalGainsReport(): Promise<CapitalGainsReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getCapitalGainsReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCapitalGainsReport();
            return result;
        }
    }
    async getFavoriteFunds(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavoriteFunds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavoriteFunds();
            return result;
        }
    }
    async getHoldings(): Promise<Array<Holding>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHoldings();
            return result;
        }
    }
    async getNextPostId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextPostId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextPostId();
            return result;
        }
    }
    async getPortfolioSummary(): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary();
            return result;
        }
    }
    async getPostById(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostById(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostById(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPosts();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPosts();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFundFavorite(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFundFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFundFavorite(arg0);
            return result;
        }
    }
    async registerUser(arg0: UserRegistration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async removeFavoriteFund(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoriteFund(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoriteFund(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateNav(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNav(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNav(arg0, arg1);
            return result;
        }
    }
    async updatePost(arg0: UpdateBlogPostInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePost(to_candid_UpdateBlogPostInput_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePost(to_candid_UpdateBlogPostInput_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePostSchedule(arg0: string, arg1: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePostSchedule(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePostSchedule(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async userSession(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.userSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.userSession();
            return result;
        }
    }
}
function from_candid_BlogPost_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): BlogPost {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_FundCategory_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundCategory): FundCategory {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Fund_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fund): Fund {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PostStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostStatus): PostStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserPortfolio_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPortfolio): UserPortfolio {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserTransactionRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserTransactionRecord): UserTransactionRecord {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPortfolio]): UserPortfolio | null {
    return value.length === 0 ? null : from_candid_UserPortfolio_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : from_candid_BlogPost_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    holdings: Array<_Holding>;
    transactions: Array<_Transaction>;
    capitalGains: _CapitalGainsReport;
}): {
    holdings: Array<Holding>;
    transactions: Array<Transaction>;
    capitalGains: CapitalGainsReport;
} {
    return {
        holdings: value.holdings,
        transactions: from_candid_vec_n21(_uploadFile, _downloadFile, value.transactions),
        capitalGains: value.capitalGains
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    amc: [] | [string];
    folioNumber: [] | [string];
    transactionType: _TransactionType;
    navPerUnit: bigint;
    bankAccount: [] | [string];
    date: _Time;
    isin: [] | [string];
    agentCode: [] | [string];
    agentName: [] | [string];
    txnDate: [] | [bigint];
    fundId: string;
    units: bigint;
    paymentMode: [] | [string];
    amount: bigint;
    remarks: [] | [string];
    subAgentCode: [] | [string];
    subAgentName: [] | [string];
}): {
    amc?: string;
    folioNumber?: string;
    transactionType: TransactionType;
    navPerUnit: bigint;
    bankAccount?: string;
    date: Time;
    isin?: string;
    agentCode?: string;
    agentName?: string;
    txnDate?: bigint;
    fundId: string;
    units: bigint;
    paymentMode?: string;
    amount: bigint;
    remarks?: string;
    subAgentCode?: string;
    subAgentName?: string;
} {
    return {
        amc: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.amc)),
        folioNumber: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.folioNumber)),
        transactionType: from_candid_TransactionType_n24(_uploadFile, _downloadFile, value.transactionType),
        navPerUnit: value.navPerUnit,
        bankAccount: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.bankAccount)),
        date: value.date,
        isin: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.isin)),
        agentCode: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.agentCode)),
        agentName: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.agentName)),
        txnDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.txnDate)),
        fundId: value.fundId,
        units: value.units,
        paymentMode: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.paymentMode)),
        amount: value.amount,
        remarks: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.remarks)),
        subAgentCode: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.subAgentCode)),
        subAgentName: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.subAgentName))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    amc: string;
    lastNavUpdate: _Time;
    name: string;
    fundType: string;
    category: _FundCategory;
    currentNav: bigint;
}): {
    id: string;
    amc: string;
    lastNavUpdate: Time;
    name: string;
    fundType: string;
    category: FundCategory;
    currentNav: bigint;
} {
    return {
        id: value.id,
        amc: value.amc,
        lastNavUpdate: value.lastNavUpdate,
        name: value.name,
        fundType: value.fundType,
        category: from_candid_FundCategory_n29(_uploadFile, _downloadFile, value.category),
        currentNav: value.currentNav
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categories: Array<string>;
    status: _PostStatus;
    title: string;
    content: Array<string>;
    createdAt: _Time;
    tags: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    updatedAt: _Time;
    scheduledAt: [] | [_Time];
}): {
    id: string;
    categories: Array<string>;
    status: PostStatus;
    title: string;
    content: Array<string>;
    createdAt: Time;
    tags: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    updatedAt: Time;
    scheduledAt?: Time;
} {
    return {
        id: value.id,
        categories: value.categories,
        status: from_candid_PostStatus_n34(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        tags: value.tags,
        author: value.author,
        readTime: value.readTime,
        summary: value.summary,
        updatedAt: value.updatedAt,
        scheduledAt: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.scheduledAt))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    amc: [] | [string];
    folioNumber: [] | [string];
    userName: string;
    principal: string;
    transactionType: string;
    navPerUnit: bigint;
    bankAccount: [] | [string];
    date: _Time;
    isin: [] | [string];
    agentCode: [] | [string];
    agentName: [] | [string];
    txnDate: [] | [bigint];
    fundId: string;
    units: bigint;
    paymentMode: [] | [string];
    amount: bigint;
    remarks: [] | [string];
    subAgentCode: [] | [string];
    subAgentName: [] | [string];
}): {
    amc?: string;
    folioNumber?: string;
    userName: string;
    principal: string;
    transactionType: string;
    navPerUnit: bigint;
    bankAccount?: string;
    date: Time;
    isin?: string;
    agentCode?: string;
    agentName?: string;
    txnDate?: bigint;
    fundId: string;
    units: bigint;
    paymentMode?: string;
    amount: bigint;
    remarks?: string;
    subAgentCode?: string;
    subAgentName?: string;
} {
    return {
        amc: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.amc)),
        folioNumber: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.folioNumber)),
        userName: value.userName,
        principal: value.principal,
        transactionType: value.transactionType,
        navPerUnit: value.navPerUnit,
        bankAccount: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.bankAccount)),
        date: value.date,
        isin: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.isin)),
        agentCode: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.agentCode)),
        agentName: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.agentName)),
        txnDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.txnDate)),
        fundId: value.fundId,
        units: value.units,
        paymentMode: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.paymentMode)),
        amount: value.amount,
        remarks: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.remarks)),
        subAgentCode: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.subAgentCode)),
        subAgentName: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.subAgentName))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sip: null;
} | {
    sell: null;
}): TransactionType {
    return "buy" in value ? TransactionType.buy : "sip" in value ? TransactionType.sip : "sell" in value ? TransactionType.sell : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    debt: null;
} | {
    elss: null;
} | {
    hybrid: null;
} | {
    equity: null;
}): FundCategory {
    return "debt" in value ? FundCategory.debt : "elss" in value ? FundCategory.elss : "hybrid" in value ? FundCategory.hybrid : "equity" in value ? FundCategory.equity : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    privateVisibility: null;
} | {
    draft: null;
}): PostStatus {
    return "published" in value ? PostStatus.published : "privateVisibility" in value ? PostStatus.privateVisibility : "draft" in value ? PostStatus.draft : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fund>): Array<Fund> {
    return value.map((x)=>from_candid_Fund_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Array<BlogPost> {
    return value.map((x)=>from_candid_BlogPost_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserTransactionRecord>): Array<UserTransactionRecord> {
    return value.map((x)=>from_candid_UserTransactionRecord_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CreateBlogPostInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBlogPostInput): _CreateBlogPostInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_FundCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundCategory): _FundCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PostStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): _PostStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionInput): _TransactionInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateBlogPostInput_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateBlogPostInput): _UpdateBlogPostInput {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categories: Array<string>;
    status: PostStatus;
    title: string;
    content: Array<string>;
    tags: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    scheduledAt?: Time;
}): {
    categories: Array<string>;
    status: _PostStatus;
    title: string;
    content: Array<string>;
    tags: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    scheduledAt: [] | [_Time];
} {
    return {
        categories: value.categories,
        status: to_candid_PostStatus_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        tags: value.tags,
        author: value.author,
        readTime: value.readTime,
        summary: value.summary,
        scheduledAt: value.scheduledAt ? candid_some(value.scheduledAt) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    amc?: string;
    folioNumber?: string;
    transactionType: TransactionType;
    navPerUnit: bigint;
    bankAccount?: string;
    isin?: string;
    agentCode?: string;
    agentName?: string;
    txnDate?: bigint;
    fundId: string;
    units: bigint;
    paymentMode?: string;
    amount: bigint;
    remarks?: string;
    subAgentCode?: string;
    subAgentName?: string;
}): {
    amc: [] | [string];
    folioNumber: [] | [string];
    transactionType: _TransactionType;
    navPerUnit: bigint;
    bankAccount: [] | [string];
    isin: [] | [string];
    agentCode: [] | [string];
    agentName: [] | [string];
    txnDate: [] | [bigint];
    fundId: string;
    units: bigint;
    paymentMode: [] | [string];
    amount: bigint;
    remarks: [] | [string];
    subAgentCode: [] | [string];
    subAgentName: [] | [string];
} {
    return {
        amc: value.amc ? candid_some(value.amc) : candid_none(),
        folioNumber: value.folioNumber ? candid_some(value.folioNumber) : candid_none(),
        transactionType: to_candid_TransactionType_n5(_uploadFile, _downloadFile, value.transactionType),
        navPerUnit: value.navPerUnit,
        bankAccount: value.bankAccount ? candid_some(value.bankAccount) : candid_none(),
        isin: value.isin ? candid_some(value.isin) : candid_none(),
        agentCode: value.agentCode ? candid_some(value.agentCode) : candid_none(),
        agentName: value.agentName ? candid_some(value.agentName) : candid_none(),
        txnDate: value.txnDate ? candid_some(value.txnDate) : candid_none(),
        fundId: value.fundId,
        units: value.units,
        paymentMode: value.paymentMode ? candid_some(value.paymentMode) : candid_none(),
        amount: value.amount,
        remarks: value.remarks ? candid_some(value.remarks) : candid_none(),
        subAgentCode: value.subAgentCode ? candid_some(value.subAgentCode) : candid_none(),
        subAgentName: value.subAgentName ? candid_some(value.subAgentName) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categories: Array<string>;
    status: PostStatus;
    title: string;
    content: Array<string>;
    tags: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    scheduledAt?: Time;
}): {
    id: string;
    categories: Array<string>;
    status: _PostStatus;
    title: string;
    content: Array<string>;
    tags: Array<string>;
    author: string;
    readTime: string;
    summary: string;
    scheduledAt: [] | [_Time];
} {
    return {
        id: value.id,
        categories: value.categories,
        status: to_candid_PostStatus_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        tags: value.tags,
        author: value.author,
        readTime: value.readTime,
        summary: value.summary,
        scheduledAt: value.scheduledAt ? candid_some(value.scheduledAt) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostStatus): {
    published: null;
} | {
    privateVisibility: null;
} | {
    draft: null;
} {
    return value == PostStatus.published ? {
        published: null
    } : value == PostStatus.privateVisibility ? {
        privateVisibility: null
    } : value == PostStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundCategory): {
    debt: null;
} | {
    elss: null;
} | {
    hybrid: null;
} | {
    equity: null;
} {
    return value == FundCategory.debt ? {
        debt: null
    } : value == FundCategory.elss ? {
        elss: null
    } : value == FundCategory.hybrid ? {
        hybrid: null
    } : value == FundCategory.equity ? {
        equity: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    buy: null;
} | {
    sip: null;
} | {
    sell: null;
} {
    return value == TransactionType.buy ? {
        buy: null
    } : value == TransactionType.sip ? {
        sip: null
    } : value == TransactionType.sell ? {
        sell: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
